version: "3"

services:
  app:
    image: raqueldesa/webacademy:latest
    container_name: webacademydemo
    restart: always
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
